// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

//import "@openzeppelin/contracts/token/ERC777/IERC777Recipient.sol";
//import "@openzeppelin/contracts/utils/introspection/IERC165.sol";

interface IERC777Recipient {
    function tokensReceived(
        address operator,
        address from,
        address to,
        uint256 amount,
        bytes calldata userData,
        bytes calldata operatorData
    ) external;
}

interface IERC165 {
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
}

abstract contract ERC165 is IERC165 {
    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId) public view virtual override returns (bool) {
        return interfaceId == type(IERC165).interfaceId;
    }
}

/**
 * @title IStakingHelper
 * @dev Interface for the StakingHelper contract
 * @notice This contract receives ERC777 tokens and automatically stakes them in configured staking contracts
 */
interface IStakingHelper is IERC777Recipient, IERC165 {
    
    /**
     * @dev Emitted when a token is sent to the contract but no staking contract is configured for it
     * @param token The address of the unsupported token
     */
    event TokenNotSupported(address indexed token);
    
    /**
     * @dev Emitted when ownership of the contract is transferred
     * @param previousOwner The address of the previous owner
     * @param newOwner The address of the new owner
     */
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    
    /**
     * @dev Returns the staking contract address for a given token
     * @param token The token address to query
     * @return The address of the staking contract, or address(0) if not configured
     */
    function stakingContracts(address token) external view returns (address);
    
    /**
     * @dev Store token-staking contract pairs (only callable by owner)
     * @param tokens Array of token addresses
     * @param _stakingContracts Array of corresponding staking contract addresses
     * @notice This function also approves the staking contracts to spend the tokens
     */
    function storePairs(address[] memory tokens, address[] memory _stakingContracts) external;
    
    /**
     * @dev Returns the address of the current owner
     * @return The owner's address
     */
    function owner() external view returns (address);
    
    /**
     * @dev Transfers ownership of the contract to a new account (only callable by current owner)
     * @param newOwner The address of the new owner
     */
    function transferOwnership(address newOwner) external;
    
    /**
     * @dev Leaves the contract without owner (only callable by current owner)
     * @notice Renouncing ownership will leave the contract without an owner,
     * thereby removing any functionality that is only available to the owner
     */
    function renounceOwnership() external;
    
    /**
     * @dev Returns true if this contract implements the interface defined by `interfaceId`
     * @param interfaceId The interface identifier, as specified in ERC-165
     * @return True if the contract implements `interfaceId`
     */
    function supportsInterface(bytes4 interfaceId) external view returns (bool);
    
    /**
     * @dev Hook called when tokens are sent to this contract via ERC777 send/operatorSend
     * @param operator The address which initiated the send (i.e. msg.sender)
     * @param from The address which previously owned the token
     * @param to The address which the tokens are being sent to (should be this contract)
     * @param amount The number of tokens being sent
     * @param userData Data generated by the user to be sent to the recipient
     * @param operatorData Data generated by the operator to be sent to the recipient
     * @notice This function will either stake the tokens via the configured staking contract
     * or return them to the sender if no staking contract is configured
     */
    function tokensReceived(
        address operator,
        address from,
        address to,
        uint256 amount,
        bytes calldata userData,
        bytes calldata operatorData
    ) external override;
} 